
insert into Groupe(id,nom)values('1','Mainz');
insert into Groupe(id,nom)values('2','Frankfurt');
insert into Groupe(id,nom)values('3','Nohfelden');
insert into Groupe(id,nom)values('4','Oldenburg');
insert into Groupe(id,nom)values('5','Erfurt');
insert into Groupe(id,nom)values('6','Rosenheim');
insert into Groupe(id,nom)values('7','Jena');
insert into Groupe(id,nom)values('8','Wadern');
insert into Groupe(id,nom)values('9','Neustadt');
insert into Groupe(id,nom)values('10','Rostock');
insert into Groupe(id,nom)values('11','Saarlouis');
insert into Groupe(id,nom)values('12','Heidelberg');
insert into Groupe(id,nom)values('13','Dresden');
insert into Groupe(id,nom)values('14','Neunkirchen');
insert into Groupe(id,nom)values('15','Mettlach');
insert into Groupe(id,nom)values('16','Mettlach J');
insert into Groupe(id,nom)values('17','Trier I');
insert into Groupe(id,nom)values('18','Trier P');
insert into Groupe(id,nom)values('19','Neuss');
insert into Groupe(id,nom)values('20','Bonn');
insert into Groupe(id,nom)values('21','Merzig');
insert into Groupe(id,nom)values('22','Stuttgart');
insert into Groupe(id,nom)values('23','Völklingen');
insert into Groupe(id,nom)values('24','Saarbrücken');
insert into Groupe(id,nom)values('25','Mannheim');
insert into Groupe(id,nom)values('26','Gera');
insert into Groupe(id,nom)values('27','Kiel');
insert into Groupe(id,nom)values('28','Marburg');
insert into Groupe(id,nom)values('29','Hamburg');
insert into Groupe(id,nom)values('30','Venlo');
insert into Groupe(id,nom)values('31','Berlin');
insert into Groupe(id,nom)values('32','Nennig');
insert into Groupe(id,nom)values('33','Bremen');
insert into Groupe(id,nom)values('34','Aachen');
insert into Groupe(id,nom)values('35','Augsburg');
insert into Groupe(id,nom)values('36','Köln');