insert into Specialisation(id,nom)('1','Santé');
insert into Specialisation(id,nom)('2','Hotelfachfrau/FSJ');
insert into Specialisation(id,nom)('3','Hotelfachfrau');
insert into Specialisation(id,nom)('4','Pflege');
insert into Specialisation(id,nom)('5','Elektroniker/FSJ');
insert into Specialisation(id,nom)('6','Pflege/FSJ');
insert into Specialisation(id,nom)('7','Hotelfachmann');
insert into Specialisation(id,nom)('8','Elektroniker');
insert into Specialisation(id,nom)('9','Hotelfachmann/FSJ');
insert into Specialisation(id,nom)('10','gebracht durch Joelson (Gera)');
insert into Specialisation(id,nom)('11','Pflegefachkraft');
insert into Specialisation(id,nom)('12','FSJ-Informatik/Pflege');
insert into Specialisation(id,nom)('13','FSJ');
insert into Specialisation(id,nom)('14','Hotelfachmann/BFD');
insert into Specialisation(id,nom)('15','Koch');
insert into Specialisation(id,nom)('16','Hotelfachfrau/BFD');
insert into Specialisation(id,nom)('17','Pflegekraft');
insert into Specialisation(id,nom)('18','Ausbi Hebamme');
insert into Specialisation(id,nom)('19','Ausbi Krankenschwester');
insert into Specialisation(id,nom)('20','hotel');
insert into Specialisation(id,nom)('21','Elektro');
insert into Specialisation(id,nom)('22','FSJ/Pflegefachkraft');
insert into Specialisation(id,nom)('23','Köchin/Hotelfachfrau');
insert into Specialisation(id,nom)('24','FSJ/Pflege');
insert into Specialisation(id,nom)('25','Köchin');
insert into Specialisation(id,nom)('26','Köchin/FSJ');
insert into Specialisation(id,nom)('27','BFD');
insert into Specialisation(id,nom)('28','Krankenschwester');
insert into Specialisation(id,nom)('29','Pflege/Hotel');
insert into Specialisation(id,nom)('30','Hotel/Pflege');
insert into Specialisation(id,nom)('31','Hotelfacahfrau');
insert into Specialisation(id,nom)('32','Hotel/BFD');
insert into Specialisation(id,nom)('33','Hotelfachkraft/Köchin');
insert into Specialisation(id,nom)('34','Koch/Elektroniker');
insert into Specialisation(id,nom)('35','Hotelfachkraft');
insert into Specialisation(id,nom)('36','Hotelkauffrau');
insert into Specialisation(id,nom)('37','Vertrag');
insert into Specialisation(id,nom)('38','Ausbi Auto');
insert into Specialisation(id,nom)('39','Pflegefachkraft/Heilerziehungspflege');
insert into Specialisation(id,nom)('40','FSJ/BFD');
insert into Specialisation(id,nom)('41','ausbildung');
insert into Specialisation(id,nom)('42','Heilerziehungspflege/Pflegefachkraft');
insert into Specialisation(id,nom)('43','Hotelfachfrau - Vertrag');
insert into Specialisation(id,nom)('44','Hotel/FSJ');
insert into Specialisation(id,nom)('45','Elektroniker oder Handarbeit');
insert into Specialisation(id,nom)('46','Elektoniker');
insert into Specialisation(id,nom)('47','Elektroniker Old'); 